pipeline {
    agent any

   

    
        
        stage('Build') {
            steps {
                dir("C:/ProgramData/Jenkins/.jenkins/workspace/my pipeline test/") {
                sh 'mvn -B -DskipTests clean package'
                }
            
            }
        }
     
    post {
       always {
          junit(testResults: 'target/surefire-reports/*.xml', 
        allowEmptyResults: true,
        
      )
      }
   } 
}
